source 'https://rubygems.org'

gem 'httparty', '~> 0.13.7'
gem 'sinatra', '~> 1.4', '>= 1.4.7'
gem 'json', '~> 1.8', '>= 1.8.3'
gem 'sqlite3'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-migrations'
gem 'dm-validations'
gem 'dm-timestamps'
